/**
 * APIMATICCalculatorLib
 *
 * This file was automatically generated by APIMATIC BETA v2.0 on 02/12/2016
 */

var configuration = {
    //The base Uri for API calls
    BASEURI : "https://examples.apimatic.io/apps/calculator"

};

module.exports = configuration;

